name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Hugging Face
        uses: huggingface/authentication-action@v1
        with:
          hf-repo-token: ${{ secrets.HF_TOKEN }}

      - name: Push to Hugging Face
        run: |
          huggingface-cli login
          huggingface-cli repo create your-model-name
          huggingface-cli repo push your-model-name

      - name: Deploy completed
        run: echo "Deployment to Hugging Face completed successfully!"